<?php
# This file was automatically generated by the MediaWiki 1.43.1
# installer. If you make manual changes, please keep track in case you
# need to recreate them later.
#
# See includes/MainConfigSchema.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# https://www.mediawiki.org/wiki/Manual:Configuration_settings

# Protect against web entry
if ( !defined( 'MEDIAWIKI' ) ) {
	exit;
}

## Uncomment this to disable output compression
# $wgDisableOutputCompression = true;

$wgSitename = "PlantLibrary";

## The URL base path to the directory containing the wiki;
## defaults for all runtime URL paths are based off of this.
## For more information on customizing the URLs
## (like /w/index.php/Page_title to /wiki/Page_title) please see:
## https://www.mediawiki.org/wiki/Manual:Short_URL
$wgScriptPath = "/mediawiki";

## The protocol and server name to use in fully-qualified URLs
// $wgServer = "http://localhost";

## The URL path to static resources (images, scripts, etc.)
$wgResourceBasePath = $wgScriptPath;

## The URL paths to the logo.  Make sure you change this from the default,
## or else you'll overwrite your logo when you upgrade!
$wgLogos = [
	'1x' => "$wgResourceBasePath/resources/assets/change-your-logo.svg",
	'icon' => "$wgResourceBasePath/resources/assets/change-your-logo.svg",
];

## UPO means: this is also a user preference option

$wgEnableEmail = true;
$wgEnableUserEmail = true; # UPO
$wgPasswordSender = "datb2207515@student.ctu.edu.vn";

$wgSMTP = [
'host' => 'ssl://smtp.gmail.com', // Gmail SMTP Server
'port' => 465,
'IDHost' => 'localhost',
'auth' => true,
'username' => 'datb2207515@student.ctu.edu.vn', // Your full Gmail address
'password' => 'gion aqaz ueyv qmaw' // The App Password you generated
];

$wgEmergencyContact = "";


$wgEnotifUserTalk = true; # UPO
$wgEnotifWatchlist = true; # UPO
$wgEmailAuthentication = true;

## Database settings
$wgDBtype = "mysql";
$wgDBserver = "localhost";
$wgDBname = "wiki_local";
$wgDBuser = "root";
$wgDBpassword = "";

// Để máy khác cũng vào được và đã tắt // $wgServer = "http://localhost";
$protocol = (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] === 'on') ? "https://" : "http://";
$host = $_SERVER['HTTP_HOST'];
$wgServer = $protocol . $host;

# MySQL specific settings
$wgDBprefix = "";
$wgDBssl = false;

# MySQL table options to use during installation or update
$wgDBTableOptions = "ENGINE=InnoDB, DEFAULT CHARSET=binary";

# Shared database table
# This has no effect unless $wgSharedDB is also set.
$wgSharedTables[] = "actor";

## Shared memory settings
$wgMainCacheType = CACHE_ACCEL;
$wgMemCachedServers = [];

## To enable image uploads, make sure the 'images' directory
## is writable, then set this to true:
$wgEnableUploads = true;
#$wgUseImageMagick = true;
#$wgImageMagickConvertCommand = "/usr/bin/convert";

# InstantCommons allows wiki to use images from https://commons.wikimedia.org
$wgUseInstantCommons = true;

# Periodically send a pingback to https://www.mediawiki.org/ with basic data
# about this MediaWiki instance. The Wikimedia Foundation shares this data
# with MediaWiki developers to help guide future development efforts.
$wgPingback = true;

# Site language code, should be one of the list in ./includes/languages/data/Names.php
$wgLanguageCode = "vi"; // Thiết lập ngôn ngữ mặc định của wiki là tiếng Việt (vi)
$wgShellLocale = "C.UTF-8";

#$wgShellLocale = "vi_VN.UTF-8";

# Time zone
$wgLocaltimezone = "Europe/Berlin";

## Set $wgCacheDirectory to a writable directory on the web server
## to make your wiki go slightly faster. The directory should not
## be publicly accessible from the web.
#$wgCacheDirectory = "$IP/cache";

$wgSecretKey = "f87644f0b1ebbd45885b2ef166fbed53253d0260418fa9257917c05cda619e30";

# Changing this will log out all existing sessions.
$wgAuthenticationTokenVersion = "1";

# Site upgrade key. Must be set to a string (default provided) to turn on the
# web installer while LocalSettings.php is in place
$wgUpgradeKey = "a2118201b0d28666";

## For attaching licensing metadata to pages, and displaying an
## appropriate copyright notice / icon. GNU Free Documentation
## License and Creative Commons licenses are supported so far.
$wgRightsPage = ""; # Set to the title of a wiki page that describes your license/copyright
$wgRightsUrl = "";
$wgRightsText = "";
$wgRightsIcon = "";

# Path to the GNU diff3 utility. Used for conflict resolution.
$wgDiff3 = "";

# The following permissions were set based on your choice in the installer
# --- CẤP QUYỀN TẠO TÀI KHOẢN (BẮT BUỘC CHO SSO) ---
# Cho phép khách vãng lai tự đăng ký (để Keycloak có thể tạo user mới)
$wgGroupPermissions['*']['createaccount'] = false;

# Cho phép hệ thống tự động tạo tài khoản khi đăng nhập qua Extension
$wgGroupPermissions['*']['autocreateaccount'] = true;
$wgGroupPermissions["*"]["edit"] = true;
$wgGroupPermissions['user']['edit'] = true;     
$wgGroupPermissions['sysop']['edit'] = true;

## Default skin: you can change the default skin. Use the internal symbolic
## names, e.g. 'vector' or 'monobook':
#$wgDefaultSkin = "vector"; 
$wgDefaultSkin = "vector-2022"; #sửa từ $wgDefaultSkin = "vector"; 


# Enabled skins.
# The following skins were automatically enabled:
wfLoadSkin( 'MinervaNeue' );
wfLoadSkin( 'MonoBook' );
wfLoadSkin( 'Timeless' );
wfLoadSkin( 'Vector' );


# Enabled extensions. Most of the extensions are enabled by adding
# wfLoadExtension( 'ExtensionName' );
# to LocalSettings.php. Check specific extension documentation for more details.
# The following extensions were automatically enabled:

wfLoadExtension( 'AbuseFilter' ); 
wfLoadExtension( 'CategoryTree' );
wfLoadExtension( 'Cite' ); 
wfLoadExtension( 'CiteThisPage' );
wfLoadExtension( 'CodeEditor' );
wfLoadExtension( 'ConfirmEdit' );
wfLoadExtension( 'DiscussionTools' );
wfLoadExtension( 'Echo' );
wfLoadExtension( 'Gadgets' );
wfLoadExtension( 'ImageMap' );
wfLoadExtension( 'InputBox' );
wfLoadExtension( 'Interwiki' );
wfLoadExtension( 'Linter' );
wfLoadExtension( 'LoginNotify' );
wfLoadExtension( 'Math' );
wfLoadExtension( 'MultimediaViewer' );
wfLoadExtension( 'Nuke' );
wfLoadExtension( 'OATHAuth' );
wfLoadExtension( 'PageImages' );
wfLoadExtension( 'ParserFunctions' );
wfLoadExtension( 'PdfHandler' );
wfLoadExtension( 'Poem' );
wfLoadExtension( 'ReplaceText' );
wfLoadExtension( 'Scribunto' );
wfLoadExtension( 'SecureLinkFixer' );
wfLoadExtension( 'SpamBlacklist' );
wfLoadExtension( 'SyntaxHighlight_GeSHi' );
wfLoadExtension( 'TemplateData' );
wfLoadExtension( 'TextExtracts' );
wfLoadExtension( 'Thanks' );
wfLoadExtension( 'TitleBlacklist' );
wfLoadExtension( 'VisualEditor' );
wfLoadExtension( 'WikiEditor' );
wfLoadExtension( 'WikiChatbot' );
$wgWikiChatbotEnabled = true;
wfLoadExtension( 'UniversalLanguageSelector' );
wfLoadExtension( 'Translate' );
wfloadExtension( 'Approve');
#wfLoadExtension( 'ContentTranslation' );

#wfLoadExtension( 'Popups' );


# End of automatically generated settings.
# Add more configuration options below.

// Bật tính năng dịch trang
$wgEnablePageTranslation = true;
//$wgPageTranslationLanguageList = ['vi', 'en']; // Ngôn ngữ hỗ trợ

// Cấu hình ngôn ngữ hệ thống
$wgLanguageCode = 'vi'; // Ngôn ngữ mặc định (tiếng Việt)
$wgDefaultLanguageVariant = 'vi';

// Cấu hình Universal Language Selector
$wgULSEnable = true;
$wgULSPosition = 'interlanguage'; // Vị trí selector ngôn ngữ
$wgULSGeoService = 'geoiplookup'; // Xác định ngôn ngữ theo vị trí địa lý
$wgULSAnonCanChangeLanguage = true; // Cho phép đổi ngôn ngữ khi chưa đăng nhập
$wgULSLanguageDetection = ['cookie', 'url', 'browser']; // Cách phát hiện ngôn ngữ

// Cấu hình Translate Extension
//$wgTranslateLanguageCodes = ['vi', 'en']; // Ngôn ngữ hỗ trợ dịch
$wgTranslateSupportedLanguages = ['en'];
$wgTranslateLanguageFallbacks['en'] = 'vi';

$wgAvailableLanguages = ['vi', 'en'];
$wgTranslateDocumentationLanguageCode = 'qqq';


$wgTranslateTranslationServices = [
    'TTMServer' => [
        'database' => false,
        'cutoff' => 0.75,
    ],
];
$wgTranslateDocumentationLanguageCode = 'qqq';

// Phân quyền dịch thuật
$wgGroupPermissions['user']['translate'] = true;
$wgGroupPermissions['translator']['translate'] = true;
$wgGroupPermissions['translator']['pagetranslation'] = true;
$wgGroupPermissions['sysop']['pagetranslation'] = true;

// Cấu hình Content Translation
$wgContentTranslationEnableApi = true;
$wgContentTranslationTranslateInTarget = true;
$wgContentTranslationSiteTemplates = [
    'wikipedia' => 'https://$1.wikipedia.org/wiki/$2',
];

// Không gian tên cho phép dịch
$wgContentTranslationNamespaceInclude = [
    NS_MAIN,
    NS_TALK,
    // ... (giữ nguyên các namespace khác)
];

// Cấu hình hiệu năng
$wgTranslateKeepMessages = true;
$wgTranslateSecondaryPermission = 'translate';

// Tự động chọn ngôn ngữ nội dung
$wgULSContentLanguageSelector = true;
$wgPageLanguageUseDB = true;

// Cấu hình ngôn ngữ mặc định
$wgDefaultUserOptions['language'] = 'vi';
$wgDefaultUserOptions['variant'] = 'vi';

// ========== CẤU HÌNH GỠ LỖI ========== //
$wgShowExceptionDetails = true;
$wgShowDBErrorBacktrace = true;
$wgGroupPermissions['user']['editinterface'] = true;

$wgRawHtml = true;


$wgVectorShowSkinPreferences = true; // Hiện tùy chọn skin trong giao diện người dùng
$wgVectorUseSidebarSearch = true;    // Sử dụng thanh tìm kiếm ở thanh bên
$wgVectorUsePageTabsForNamespaces = true; // Dùng tab để phân biệt namespace

#Không thêm được code từ web
$wgHooks['SkinBuildSidebar'][] = function ($skin, &$bar) {
    $bar['Công cụ dữ liệu'] = [
        [
            'text' => '🚀 Mở Jupyter Lab',
            'href' => 'http://localhost:8000',
            'id'   => 'n-jupyterhub',
            'active' => true
        ]
    ];
    return true;
};


// wfLoadExtension( 'ApiData' ); 

// Them donate button vao sidebar
// wfLoadExtension( 'DonateButton' );
// $wgDonateButton = true;
// $wgDonateButtonURL = "https://example.org";

// Tich hop keycloack
wfLoadExtension( 'PluggableAuth' );
wfLoadExtension( 'OpenIDConnect' );

$wgPluggableAuth_Config[] = [
    'plugin' => 'OpenIDConnect',
    'data' => [
        'providerURL' => 'http://localhost:8080/realms/my_realm', 
        'clientID' => 'my_client',
        'clientsecret' => 'qqmDtLdn3vjTvl0rkhGqD6orwSRZzvXM' 
    ]
];


$wgOpenIDConnect_SingleLogout = true; // Dang xuat hoan toan
$wgDBserver = "127.0.0.1:3306"; // Can de update db cho OpenIDConnect
$wgShowExceptionDetails = true;
$wgDebugLogFile = "C:/xampp/htdocs/mediawiki/debug.log";
error_reporting( -1 );
ini_set( 'display_errors', 1 );

